### PR TITLE
Update Guava & Jackson

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Review by kokosing — COMMENTED** [review]
Can you please try to run Trino Ci for this change? Jackson updates are known for causing issues.

**Comment by wendigo** [comment]
> Can you please try to run Trino Ci for this change? Jackson updates are known for causing issues.

I'll do it but airbase itself is unusable right now due to modernizr update which brings new rules that we don't follow yet

**Comment by wendigo** [comment]
@kokosing it works

**Comment by kokosing** [comment]
Lgtm from me. I cannot merge it as I am not maintainer here. Thank you for checking!

**Comment by wendigo** [comment]
@martint can you review it please?

**Pull request merged**
