### PR TITLE
Update jackson to 2.11.1

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Review by kokosing — CHANGES_REQUESTED** [review]
@lukasz-walkiewicz is this working with Presto?

**Comment by findepi** [comment]
> @lukasz-walkiewicz is this working with Presto?

https://github.com/prestosql/presto/blob/4ab076a0a9e672047f532339d1cffd24f59da701/pom.xml#L65

**Comment by kokosing** [comment]
Thanks. FYI https://github.com/FasterXML/jackson-databind/pull/2894

**Comment by wendigo** [comment]
> @lukasz-walkiewicz is this working with Presto?

Yep. It was upgraded recently and that's why I'm updating this here (and I will update airlift/json as well to use new airbase once it's released)

**Pull request merged**
