### PR TITLE
update Guava to 30.0

### PR DESCRIPTION
**Pull request by RaymondWaterlooLi**

### CODE REVIEW

**Comment by kokosing** [comment]
In order to verify if it is not a breaking change we could update guava in presto 30.0 and see if it is passing automation. Same thing we need to do for airlift.

**Comment by wendigo** [comment]
Can be closed @kokosing. Guava was updated  in https://github.com/airlift/airbase/commit/47654df9578146d08a43501c98f76b0318b14d56

**Comment by kokosing** [comment]
@findepi Can you please close it?

**Comment by findepi** [comment]
Covered in https://github.com/airlift/airbase/pull/250

@RaymondWaterlooLi sorry that I did not merge yours.
I did not remember about it.

**Pull request closed without merging**
