### PR TITLE
Update guava to 0.20

### PR DESCRIPTION
**Pull request by kokosing**
Update guava to 0.20

### CODE REVIEW

**Comment by wenleix** [comment]
It looks like with guava upgrade to 20, the latest code of Presto is failing to compile with the following error (I changed to use airbase 60-SNAPSHOT in Presto root pom.xml):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project presto-main: Compilation failure: Compilation failure:
[ERROR] /Users/wxie/Code/presto-all/presto/presto-main/src/main/java/com/facebook/presto/operator/scalar/ScalarFunctionImplementation.java:[62,17] reference to checkArgument is ambiguous
[ERROR] both method checkArgument(boolean,java.lang.String,java.lang.Object,java.lang.Object) in com.google.common.base.Preconditions and method checkArgument(boolean,java.lang.String,int,java.lang.Object) in com.google.common.base.Preconditions match
[ERROR] /Users/wxie/Code/presto-all/presto/presto-main/src/main/java/com/facebook/presto/operator/NestedLoopJoinPagesSupplier.java:[49,16] no suitable method found for transform(com.google.common.util.concurrent.SettableFuture<com.facebook.presto.operator.NestedLoopJoinPages>,com.google.common.util.concurrent.AsyncFunction<com.facebook.presto.operator.NestedLoopJoinPages,com.facebook.presto.operator.NestedLoopJoinPages>)
[ERROR] method com.google.common.util.concurrent.Futures.<I,O>transform(com.google.common.util.concurrent.ListenableFuture<I>,com.google.common.base.Function<? super I,? extends O>,java.util.concurrent.Executor) is not applicable
[ERROR] (cannot infer type-variable(s) I,O
[ERROR] (actual and formal argument lists differ in length))
[ERROR] method com.google.common.util.concurrent.Futures.<I,O>transform(com.google.common.util.concurrent.ListenableFuture<I>,com.google.common.base.Function<? super I,? extends O>) is not applicable
[ERROR] (cannot infer type-variable(s) I,O
...
```

Is there anything I should do to fix this?

**Comment by kokosing** [comment]
The reason why I wanted to upgrade guava is not so much important (I wanted
to use some methods which was added to recent version).  So if it is not
trivial to fix this compilation failures I would just revert the upgrade of
guava version.

**Comment by martint** [comment]
No, we should just fix whatever compilation issues occur.

**Comment by kokosing** [comment]
Ok, I will try to migrate Presto to new version of guava.

**Comment by kokosing** [comment]
See https://github.com/prestodb/presto/pull/6995

**Comment by electrum** [comment]
This commit is missing release notes

**Comment by kokosing** [comment]
@electrum See https://github.com/airlift/airbase/pull/99 where missing release note is addressed

**Pull request merged**
