### PR TITLE
Fix javadoc plugin configuration when JDK preview features used

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
cc @electrum @wendigo

**Comment by findepi** [comment]
relates to https://github.com/airlift/airbase/pull/404

**Comment by wendigo** [comment]
This still doesn't work in IntelliJ. I think that this is due to the fact that `air.compiler.enable-preview` is evaluated to produce `surefireEnablePreview` in the `build-helper-maven-plugin` which is not something that IntelliJ understands and support.

**Comment by wendigo** [comment]
I think that instead of `air.compiler.enable-preview` we should introduce `air.compiler.extra-args`

**Comment by wendigo** [comment]
@findepi this would work

**Comment by findepi** [comment]
@electrum would you like to take a look?

**Review by electrum — APPROVED** [review]

**Pull request merged**
