### PR TITLE
Replace checkstyle illegal import rules with RestrictImports

### PR DESCRIPTION
**Pull request by wendigo**
Alternative approach to https://github.com/airlift/airbase/pull/355 as suggested by @electrum 

For reference: https://github.com/skuzzle/restrict-imports-enforcer-rule

### CODE REVIEW

**Comment by wendigo** [comment]
cc @electrum @hashhar @kokosing @findepi

**Comment by hashhar** [comment]
errorprone profile isn't enabled by default locally so devs won't catch until these reach CI - just something to consider

**Comment by wendigo** [comment]
@hashhar enforcer is enabled on a default profile. I've checked that PR with the minimal set of flags

**Review by electrum — APPROVED** [review]

**Comment by hashhar** [comment]
> @hashhar enforcer is enabled on a default profile. I've checked that PR with the minimal set of flags

Ah, I was confused between errorprone and enforcer plugins. 😄

**Pull request merged**
