### PR TITLE
Add hook for altering surefire JVM argLine

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
BTW what does this stand for?
https://github.com/airlift/airbase/blob/087343ca0153fd0f80e2e620c58c6e660f917449/airbase/pom.xml#L434

**Comment by electrum** [comment]
Update CHANGES

**Comment by electrum** [comment]
`${argLine}` is used for Jacoco: https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html

**Comment by findepi** [comment]
> `${argLine}` is used for Jacoco: https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html

thanks! does it matter we use `$` syntax vs `@{argLine}` in their docs?

**Pull request merged**
